### ISSUE TITLE
Initial experimentation roadmap

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/lox#1]
Unsorted, random things to do:

### Week 2018-12-03: *"Finish" sink/source system*
- [x] Finish `convert` tool for now (if that works, the sink/source system is probably fine)
- [ ] Read into a mesh and `PropMap`s where we can decide what kinds of properties we want (e.g. read this into a mesh and position prop map). 
- [x] PLY Source impl
- [ ] Adjust and add tests 
- [ ] Adjust and add documentation

### Week 2018-11-26
- ~~*"Finish" sink/source system*~~
- Sink:
    - [ ] ~~Read into a mesh and `PropMap`s where we can decide what kinds of properties we want (e.g. read this into a mesh and position prop map)~~ -> postponed
    - [x] ~~STL file~~ → No! Files cannot implement `Sink` due to source-determined ordering of `add`-opertions
- Source:
    - [x] Implement `map_vertex` and `map_face` 
- [x] Evtl PLY Reader
- [ ] ~~Evtl PLY Sink/Source impl~~  -> postponed
- [ ] ~~Adjust and add tests~~ -> postponed
- [ ] ~~Adjust and add documention~~ -> postponed

### Later
- [x] Implement HEM
- [x] Think about mesh traits
