### ISSUE TITLE
Tracking issue: GAT improvements

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/lox#7]
This issue collects all major parts of the library that can be improved with generic associated types. This library won't be released as `1.x` before GATs have landed and these improvements have been implemented, as they a central to a fast and convenient API.

- [x] ~~Element iterators: `Explicit{Edge, Face, Vertex}::{edges, faces, vertices}()` currently return `Box<Iterator>`. Instead, those traits should have a GAT `{Edge, Face, Vertex}Iter<'s>` instead which is returned by the methods.~~ -> #32
- [x] ~~`PropMap`: the trait currently uses a hack from the `boo` module.~~ -> done
- [ ] `IntoMeshWriter` could also move its parameters to the function and an GAT
